#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 22 16:44:14 2018

@author: lfz001
"""
###########爬取京东电脑的价格信息

import re
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import csv
import requests
import json
import string
import random

header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.2107.204 Safari/537.36'}

url0='https://list.jd.com/list.html?cat=670,671,672&page='
url1='&sort=sort_totalsales15_desc&trans=1&JL=6_0_0#J_main'
urls=[]
for i in range(1021):
    url00=url0+str(i+1)+url1
    urls.append(url00)
    
    
all_url=[]
def zhuaqu1(url):
    html = requests.get(url,headers = header)
    soup = BeautifulSoup(html.text,'html.parser')
    href=soup.find_all('div',attrs={'class':"gl-i-wrap j-sku-item"})
    for  hh in href :
        urlss=hh.a.get('href')
        all_url.append(urlss)
    return all_url  
#soup.find_all('div',attrs={'class':"gl-i-wrap j-sku-item"})[0].a.get('href')


for i in range(0,1021):
    try:
        zhuaqu1(urls[i])
        print(i)
    except :
        print ('第'+str(i)+'出错了')
        break

#len(all_url)  xx=pd.Series(all_url)  xx.to_csv('aa555.csv')

aa=pd.read_csv('aa11.csv')
all_url=aa['wanzhi']

all_price=[]

# ''.join([random.choice(string.digits) for i in range(22)])  加入随机数字后可以有效地防止被封ip地址
for i in range(0,61253):
    try:
        n=re.findall("\d+",all_url[i])[0]
        pduid = ''.join(random.sample(string.digits, 10)+random.sample(string.digits, 10)+random.sample(string.digits, 2))
        nnn='http://p.3.cn/prices/mgets?skuIds=J_'+n+'&pduid='+pduid
        html = requests.get(nnn,headers = header)
        soup = BeautifulSoup(html.text,'html.parser')
        soup=str(soup)
        soup=json.loads(soup)
        price=soup[0]['p']
        all_price.append(price)
        print(str(i))
    except :
        print ('第'+str(i)+'价格出错了')
        break
    
## yy=pd.Series(all_price) yy.to_csv('price.csv')



lan=len(yy)
hou=[]
for j in range(0,lan):
    hous=float(yy[j])%100
    hou.append(hous)

## hou=pd.Series(hou) hou.to_csv('price_hou.csv')

    
        
 


 
 
